<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tungus" nsURI="urn:org.nasdanika.tungus" nsPrefix="tungus">
  <eClassifiers xsi:type="ecore:EClass" name="Competitor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualCompetitor" eSuperTypes="#//Competitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="#//Competitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Competition" abstract="true">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Competitor"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" lowerBound="2"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//Participant">
        <eTypeArguments eTypeParameter="#//Competition/C"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualCompetition">
    <eGenericSuperTypes eClassifier="#//Competition">
      <eTypeArguments eClassifier="#//IndividualCompetitor"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeamCompetition">
    <eGenericSuperTypes eClassifier="#//Competition">
      <eTypeArguments eClassifier="#//Team"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" abstract="true">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Competitor"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="competitor" lowerBound="1">
      <eGenericType eTypeParameter="#//Participant/C"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualParticipant">
    <eGenericSuperTypes eClassifier="#//Participant">
      <eTypeArguments eClassifier="#//IndividualCompetitor"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeamParticipant">
    <eGenericSuperTypes eClassifier="#//Participant">
      <eTypeArguments eClassifier="#//Team"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
